server:
  port: 8120

spring:
  profiles:
    active: dev
  application:
    name: service-sms
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  rabbitmq:
    host: 192.168.163.128
    port: 5672
    virtual-host: /srb
    username: srb
    password: 123456
aliyun:
  sms:
    region-id: 填写自己的
    key-id: 填写自己的
    key-secret: 填写自己的
    template-code: 填写自己的
    sign-name: 尚融宝
#配置feign的连接超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置
  sentinel:
    enabled: true
#开启日志显示
logging:
  level:
    com.atguigu.srb.sms.client.CoreUserInfoClient: DEBUG #以什么级别监控哪个接口